apiVersion: v1
kind: ConfigMap
metadata:
  name: timetagger-config
  namespace: timetagger
data:
  TIMETAGGER_BIND: "0.0.0.0:80"
  TIMETAGGER_DATADIR: "/home/timetagger/_timetagger"
  TIMETAGGER_LOG_LEVEL: "info"