apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timetagger-data
spec:
  accessModes:
    - ReadWriteOnce # Change to ReadWriteMany if using NFS/Ceph for multi-pod
  resources:
    requests:
      storage: 1Gi

