apiVersion: v1
kind: Secret
metadata:
    name: timetagger-credentials
    namespace: timetagger
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:DyBLdTeRrpCURHOZL1B7+rT4TNOIpyZ9v/QlrB48PtYrxQwH+HLMOfh4gZHOHZgbnNVSbhHdMJ4aIjGCwwTKpfQ=,iv:xoHapo882t7ITArdnwq6tDzo2+mX8HUZkeXtd7yUp/4=,tag:O7sO1kP7qX7T87jezE5Agw==,type:str]
sops:
    age:
        - recipient: age1nd8vdr9jddp5fusjrfsdhs9hjaa4jlenrpe52jx4hkx8ttjeavpq80mxdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWGdpTDBlQXBhZlZ0MG0v
            NkUwVDVwMHpvTkQ3VWtLSzNWRFRUU1NYRmswCktNU3FNUTdTTTk5a0pHNWxEMXJY
            bVNxUTBhRU8zenVlTDQ4KzR6VHFGbEUKLS0tIDFOaHgyRU9lcXVkREhqNEtQRy8r
            TEtscXhQWlIwU2RTODhyUHRHdEQ1MWsKvRlvGCCpQfMcZnlXpnXZywpTYeb1AgiW
            8fPVhuVIaT+rUbQ09qFnDbcB6PCX8ktrMtVB1t1vipjDhCfnabx4gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T18:12:48Z"
    mac: ENC[AES256_GCM,data:y6F4th8CxEGdhpKLFTVdfNCsqkWZTfJW/twWCOLbuMG/ND9Nd4659pYTXHVQs1CDAS50ujGuqwXV4wlOcOa4+XAh1pVvclbzLC39PIKUmf50Edp8rn1v3LU/3d2o16w3hKaIhTNdfQyS80ISIiNU5tzr5G0gBA3lZohqrNT6LJo=,iv:hGEJggb8/qW5HygbYqsZ0e6sdvdB2iIZdfgrbki20TM=,tag:iI7jK9OIX4FZhc1vNaLHGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2