apiVersion: v1
kind: Secret
metadata:
    name: timetagger-user-cred
    namespace: timetagger
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:CA6WnlLpace56PwZs//bWj1tXMPBOFNtdaqk13Qpzp/g5KWyj+YA5XVGK0cZe2YSSfh31mDmq9H+trrwKGpfnSD8zKufVdQ/CHagyfWlf1hyNwWcAmLwwLYEN39VsCFGbEFzDnMeJ2oFx0l3EPL5FAX1NvAQtA8zhuQFH1+v0LKdoMPS72k=,iv:X6/QRHpKbSDtG/06a2JS97ZAWjth6k9GcxHutWfz0nU=,tag:bK//9vhbVbtpGnLz/wfQiw==,type:str]
sops:
    age:
        - recipient: age1nd8vdr9jddp5fusjrfsdhs9hjaa4jlenrpe52jx4hkx8ttjeavpq80mxdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K3lmY1FtaUd6UzA4ZCty
            UVlQU3VtZlUzZnJvU2Y4V2JyRkJsL2NDQTJvClhKejVSQmF1SmVFbU8vandGTUM4
            M1g1QlVtQkdybGlmQ3pIT0ZZcFcrYVEKLS0tIC8xeGpzZzg4SUx0VU11eGM5QlRQ
            dmMwbFZKSzhOeDNONXdpS2tVZll4ZE0K9DhUDZnefWA/425L5FpTedblqUK+PnzP
            281UxoLMEqDZsaiQkK7J3C1wvExpgoATwhYcxLq1MOfM70ZTezMhEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T18:29:52Z"
    mac: ENC[AES256_GCM,data:OakEThiouthM02EKd7dRUT+PgVKTthf5IMjYWookqpS6tQNcXszKfxHuSCnx+CE6QC3NJTMfeUgyrpnylEzfL5GqYIb1UuLrz9feF/AqrjQerGsVziuSGsUZWd1AtYB/ZG2RnKr3vrGKRRlMS1ZqCBUOzwa2mC8tFgi8fkc2CsQ=,iv:2h4EtG53bh6pVgt5EwaNqfpTboIXD9AwqAb/IgP3er0=,tag:R5LOTcIP5BzwjPQUrwys4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2