apiVersion: v1
kind: Secret
metadata:
    name: timetagger-credentials
    namespace: timetagger
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:N9YKA7qUgmGQ1B0ySdYkQYqsgW3K/vupoxTXjiSqsrezTwRQRWkJoECL2r3t0jPrPGPkgHIRcQgZZmppx92msMYyI6M=,iv:4qMGu372ZPIkvOdUAbxobTc6hNt42LULtkDMLw47DBI=,tag:gjJ4Op0cI7df/RmeZnSMFg==,type:str]
sops:
    age:
        - recipient: age1nd8vdr9jddp5fusjrfsdhs9hjaa4jlenrpe52jx4hkx8ttjeavpq80mxdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaXZNOGkzb1c2bG85dkRx
            RGxHZTd0NmQrcXR4NHpRZys1WHl5T3I5VjFVClRmQWEvOW04eFQ3dTFreDI2Q0RY
            cHIzUUFMSlR6WEJlM3N5a1BvME15S0kKLS0tIFUzcmQwRTlWQWQ5eHgrcHBHWmNn
            SFJxSURKemJ3NHVST1hFOGNHWEpLNGcKXcGxYZ649re1acKwW8vehioSgPX83KCm
            JFPdyExjoXvjtWHvbWQjSdP2mu/QTzMI9fFQMOifrKnWMXPx2AGR7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T17:54:50Z"
    mac: ENC[AES256_GCM,data:8ZVGFYMWHYNG29VtyN4MuSG2+qpD6TZlZ7QTehZt3tVqf2wZXNiEyn2Vj3Ficz9c1KQnoft14qHLa32KUf7c/eFPf6gb/Eg4nOk+CdG068ytD7aZ0pm7yWf/5JS5badgKIMylvB6uNc7XlJWX574dXU6m15gXxzFjVx5XWtM4FY=,iv:uGne2tU6mV5eYNmxOOeOhkn6KJiIsCIBGk7b4NZQuIw=,tag:dzLmfnv1FvniEy0Av3rYhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
