apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:MFQnOCCX0bFbZI2ZcYK3gXyPTTSZSbNC3p4G+tIXD/SHKKQfEcO4WvbvhBjjD9yeSCp/O0BSTY1dsrOgEUriWR47+anyDDqucVamidFWOdnNudo2JdEcBRyo5nV56Bj3iTVoDO5Fxi/dBQLtHuGp2+CaG0/v3YnOpcXJ6V+nwSpu1FiXoPVk2Nb9IF+0ljSiiBjF3kuNen7A94AgGOl0QYLR2LhYSQcGIxG5lsVR66fPQPA0bYMihTjjai6DYS6RyRyrfXzUZoZ5MOta7nWlD4Ss+i6T3IrpD3n7ScuWxj98pO1eDx06JIFKNPE=,iv:cLgLZhmZu1RHv+aBJv9Us4ksSJv7IZKJByVQdLVDRDE=,tag:bAERK6yxknCsHa8kYwyVTw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
type: Opaque
sops:
    age:
        - recipient: age1nd8vdr9jddp5fusjrfsdhs9hjaa4jlenrpe52jx4hkx8ttjeavpq80mxdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNam1wbnk2aDZraUhnazZh
            cDhubnJWNTliQ1pQZzh0NEhYWXRneEVHNTMwCkZJcUYzMnNVV1FSemoyNm50Vklv
            cVZKbW05T1YxRXJVTE4wTXZPOE9sRVkKLS0tIEgyT1FHOU56end3c2VWWmVXUmFx
            UEtTMnpyTXREelBRZ0RyakFiT2Fna0UKKJ3myVUZXn594NUxIQlAFHv3Tsn0zeCk
            /0rgq/TP1lOfjs4tfKd5Oa6+d1OdeujggFm+aT5oPHl8Xu1wUEoRLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-01T15:03:52Z"
    mac: ENC[AES256_GCM,data:57ENmYfDUFN002h+yf1VOC7W5d+z9SSUPUS0653qTjoWgOLPpfaHXVzmH6sSkZAKSsjUmgm36Pf9xRiEnV1peOexBut2G+5oa0qMoErpDL5RvoZnF9a9GfL9Ix+7ty9JoIggSz1dai1B4aIidUVoNUY+I5/OYMAC/0NEoWIIoJM=,iv:PdWyHvZb7WkLi0dVcQyhz1g/4H2F+Aja/S5Nm+uAmv0=,tag:xM1+c8szTt48t1ayH1xjbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
