apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app-pvc    # /var/www/html - app files, config
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce # local-path only supports `ReadWriteOnce`
  resources:
    requests:
      storage: 1Gi
  storageClass: local-path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc   # user uploaded files, photos, docs
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 10Gi
  storageClass: local-path
  