apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg.yaml
  - clusters.yaml
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - storage.yaml
  #- values.yaml