apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.10.3"
      sourceRef:
        kind: HelmRepository
        name: immich-charts
        namespace: immich
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled

  values:
    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc  # the pre-created PVC
    machine-learning:
      persistence:
        cache:
          type: persistentVolumeClaim  # change from default emptyDir
          size: 10Gi
          accessMode: ReadWriteOnce # had ReadWriteMany so multiple Immich pods access it simultaneously, but local-path only supports `ReadWriteOnce`
          # storageClass: your-class
    valkey:
      enabled: true
    env:
      DB_HOSTNAME: immich-postgresql-rw.immich.svc.cluster.local
      DB_DATABASE_NAME: immich
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-secret
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-postgres-secret
            key: password
      DB_VECTOR_EXTENSION: vectorchord